version: "3.3"

services:

  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

  redis:
    image: redis
    container_name: redis

  s3:
    image: minio/minio
    container_name: s3
    ports:
      - "9000:9000"
    volumes:
      - ./storage/minio:/data
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
    command: server --address 0.0.0.0:${MINIO_PORT} /data

  mongo_api:
    build: ./src
    image: go_test_api
    container_name: mongo_api
    hostname: mongo_api
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.mongo_api.rule=Path(`/mongo`)"
      - "traefik.http.routers.mongo_api.entrypoints=web"
    environment: 
      - MONGO_DSN=mongodb://mongo:27017
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}

  redis_api:
    build: ./src
    image: go_test_api
    container_name: redis_api
    hostname: redis_api
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.redis_api.rule=Path(`/redis`)"
      - "traefik.http.routers.redis_api.entrypoints=web"
    environment: 
      - REDIS_DSN=redis://redis:6379

  s3_api:
    build: ./src
    image: go_test_api
    container_name: s3_api
    hostname: s3_api
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.s3_api.rule=Path(`/s3`)"
      - "traefik.http.routers.s3_api.entrypoints=web"
    environment:
      - AWS_ACCESS_KEY_ID=${MINIO_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${MINIO_SECRET_KEY}
      - AWS_REGION=us-west-2
      - S3_ENDPOINT=http://s3:${MINIO_PORT}
      - S3_DISABLE_SSL=1
      - S3_FORCE_PATHSTYLE=1
